Fix things in pass command, + add settings and gen

diff --git a/risq b/risq
--- a/risq
+++ b/risq
@@ -1,12 +1,4 @@
-#!/usr/bin/env bash
-# This script was generated by bashly 0.8.6 (https://bashly.dannyb.co)
-# Modifying it manually is not recommended
-
-# :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n"
-  exit 1
-fi
+#!/usr/bin/env zsh
 
 # :command.master_script
 
@@ -65,7 +57,7 @@ risq_pass_usage() {
   fi
 
   printf "Usage:\n"
-  printf "  risq pass [COMMAND] [ARGUMENTS...]\n"
+  printf "  risq pass [COMMAND] [...]\n"
   printf "  risq pass --help | -h\n"
   echo
 
@@ -84,11 +76,6 @@ risq_pass_usage() {
     # :argument.usage
     echo "  COMMAND"
     printf "    Pass command to use\n"
-    echo
-
-    # :argument.usage
-    echo "  ARGUMENTS..."
-    printf "    Arguments to give to pass program\n"
     echo
 
   fi
@@ -262,21 +249,181 @@ config_has_key() {
     [[ $(config_get "$1") ]]
 }
 
+# src/lib/log.sh
+
+
+# Section is set either by functions or simple calls,
+# so that logging can inform on the component working.
+section='risks'
+
+# When multiple sections are used within a single risks
+# operation, we padd them, for clearer/better aesthetics.
+section_padding=0
+
+# Simple way of setting the section and to update the padding
+_in_section ()
+{
+    section="$1"
+    if [[ -n "${2}" ]]; then
+        section_padding="$2"
+    fi
+}
+
+
+function is_verbose_set () {
+    if [[ "${args[--verbose]}" -eq 1 ]]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+# Messaging function with pretty coloring
+function _msg()
+
+{
+    # Check if we have been provided a section name,
+
+    # and if not, that the section is set to a default.
+    if [[ ${#@} -lt 3 ]]; then
+        local progname="$section"
+        if [[ -z "$progname" ]]; then
+            progname='risks'
+        fi
+        local msg="$2"
+    else
+        local progname="$2"
+        local msg="$3"
+    fi
+
+    # Padd the program/section name
+    progname="$(printf %"${section_padding}"s "${progname}")"
+
+    # Apply any translation for non-english users
+    # local i
+    # command -v gettext 1>/dev/null 2>/dev/null && msg="$(gettext -s "$3")"
+    # for i in {3..${#}}; do
+    # 	msg=${(S)msg//::$(($i - 2))*::/$*[$i]}
+    # done
+
+    local command="print -P"
+    local pchars=""
+    local pcolor="normal"
+    local fd=2
+    local -i returncode
+
+    case "$1" in
+        inline)
+            command+=" -n"; pchars=" > "; pcolor="yellow"
+            ;;
+        message)
+            pchars=" . "; pcolor="white"
+            ;;
+        verbose)
+            pchars="[D]"; pcolor="blue"
+            ;;
+        success)
+            pchars="(*)"; pcolor="green"
+            ;;
+        warning)
+            pchars="[W]"; pcolor="yellow"
+            ;;
+        failure)
+            pchars="[E]"; pcolor="red"
+            returncode=1
+            ;;
+        print)
+            progname=""
+            fd=1
+            ;;
+        *)
+            pchars="[F]"; pcolor="red"
+            msg="Developer oops!  Usage: _msg MESSAGE_TYPE \"MESSAGE_CONTENT\""
+            returncode=127
+            ;;
+    esac
+
+    [[ -n $_MSG_FD_OVERRIDE ]] && fd=$_MSG_FD_OVERRIDE
+
+    # If there is a log-file specified with flag --log-file,
+    # output the message to it, instead of the current file descriptor
+    logfile="${args[--log-file]}"
+    if [[ -n "${logfile}" ]]; then
+        ${=command} "${progname}" "${pchars}" "${msg}" >> "$logfile"
+        return $returncode
+    fi
+
+    # Else, print to stdout, with colors
+    if [[ -t $fd ]]; then
+        [[ -n "$progname" ]] && progname="$fg[magenta]$progname$reset_color"
+        [[ -n "$pchars" ]] && pchars="$fg_bold[$pcolor]$pchars$reset_color"
+        msg="$fg[$pcolor]$msg$reset_color"
+    fi
+
+    ${=command} "${progname}" "${pchars}" "${msg}" >&"$fd"
+    return $returncode
+}
+
+function _message() {
+    local notice="message"
+    [[ "$1" = "-n" ]] && shift && notice="inline"
+    option_is_set -q || _msg "$notice" "$@"
+    return 0
+}
+
+function _verbose() {
+    is_verbose_set && _msg verbose "$@"
+    return 0
+}
+
+function _success() {
+    option_is_set -q || _msg success "$@"
+    return 0
+}
+
+function _warning() {
+    option_is_set -q || _msg warning "$@"
+    return 1
+}
+
+# failure first prints the message we have passed following the catch
+# of an error exit code, and then looks at the contents of erroring
+# command's stderr buffer, which is printed just below our message.
+# We then exit the program.
+function _failure()
+
+{
+    typeset -i exitcode=${exitv:-1}
+
+    _msg failure "$@"
+    if [[ -n "$COMMAND_STDERR" ]]; then
+        _msg inline "$COMMAND_STDERR"
+    fi
+
+    # Be sure we forget the secrets we were told
+    exit "$exitcode"
+}
+
+function _print() {
+    option_is_set -q || _msg print "$@"
+    return 0
+}
+
 # src/lib/pass.sh
 
 # Ask the vault to show the ouput of a password
 pass_show ()
 {
     local password
-    password=$(qvm-pass "${@}" | head -n 1)
+    password=$(qvm-pass show "${@}" | head -n 1)
 
-	#copies the password to clipboard
-	echo -n "${password}" | xclip -selection clipboard
-	echo "Password has been saved in clipboard"
-	echo "Press CTRL+V to use the content in this qube"
-	echo "Press CTRL+SHIFT+C to share the clipboard with another qube"
-	echo "In the other qube, press CTRL+SHIFT+v and then CTRL+V to use the clipboard content"
-	echo "Local clipboard will be erased is ${PASS_TIMEOUT} seconds"
+    #copies the password to clipboard
+    echo -n "${password}" | xclip -selection clipboard
+    echo "Password has been saved in clipboard"
+    echo "Press CTRL+V to use the content in this qube"
+    echo "Press CTRL+SHIFT+C to share the clipboard with another qube"
+    echo "In the other qube, press CTRL+SHIFT+v and then CTRL+V to use the clipboard content"
+    echo "Local clipboard will be erased is ${PASS_TIMEOUT} seconds"
     ( sleep "${PASS_TIMEOUT}"; echo -n "" |xclip -selection clipboard;) &
 }
 
@@ -285,13 +432,13 @@ pass_show ()
 pass_show_once ()
 {
     local password
-    password=$(qvm-pass "${@}" | head -n 1)
+    password=$(qvm-pass show "${@}" | head -n 1)
 
-	#copies the password to clipboard
-	echo -n "${password}" | xclip -selection clipboard -loops 1
+    #copies the password to clipboard
+    echo -n "${password}" | xclip -selection clipboard -loops 1
 
-	echo "Password has been saved in clipboard"
-	echo "Local clipboard will be erased after 1 use"
+    echo "Password has been saved in clipboard"
+    echo "Local clipboard will be erased after 1 use"
 }
 
 # src/lib/utils.sh
@@ -317,11 +464,11 @@ risq_pass_command() {
 
   local command arguments
   command="${args[command]}"
-  arguments=( "${args[arguments]}" )
+  arguments=( "${other_args[*]}" )
 
   case "${command}" in
       (show) pass_show_once "${arguments[@]}" ;;
-      *) qvm-pass "${arguments[@]}" ;;
+      *) qvm-pass "$command" "${arguments[@]}" ;;
   esac
 
 }
@@ -420,23 +567,19 @@ risq_pass_parse_requirements() {
     case "$key" in
 
     -?* )
-      printf "invalid option: %s\n" "$key"
-      exit 1
+      other_args+=("$1")
+      shift
       ;;
 
     * )
       # :command.parse_requirements_case
-      # :command.parse_requirements_case_repeatable
+      # :command.parse_requirements_case_catch_all
       if [[ -z ${args[command]+x} ]]; then
 
         args[command]=$1
         shift
-      elif [[ -z ${args[arguments]+x} ]]; then
-
-        args[arguments]="\"$1\""
-        shift
       else
-        args[arguments]="${args[arguments]} \"$1\""
+        other_args+=("$1")
         shift
       fi
 
