Add beginning of verify <onion> command - Command structure and validations - Some code - Base completions - Added lib code

diff --git a/risq b/risq
--- a/risq
+++ b/risq
@@ -1,9 +1,13 @@
 #!/usr/bin/env zsh
 
+# :command.master_script
+
+# :command.version_command
 version_command() {
   echo "$version"
 }
 
+# :command.usage
 risq_usage() {
   if [[ -n $long_usage ]]; then
     printf "risq - RISKS AppVM client (wrapper around pseudo pass/tomb utils)\n"
@@ -20,14 +24,17 @@ risq_usage() {
   printf "  risq [command] --help | -h\n"
   printf "  risq --version | -v\n"
   echo
-
+  # :command.usage_commands
   printf "Commands:\n"
-  echo "  pass   Use the password-store in vault"
+  echo "  pass     Use the password-store in vault"
+  echo "  verify   Verify an onion link signature"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
 
+    # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
     echo
@@ -38,6 +45,7 @@ risq_usage() {
   fi
 }
 
+# :command.usage
 risq_pass_usage() {
   if [[ -n $long_usage ]]; then
     printf "risq pass - Use the password-store in vault\n"
@@ -54,25 +62,79 @@ risq_pass_usage() {
   printf "  risq pass --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
 
+    # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
     echo
 
+    # :command.usage_args
     printf "Arguments:\n"
 
+    # :argument.usage
     echo "  COMMAND"
     printf "    Pass command to use\n"
     echo
 
+    # :command.footer
     printf "A Qubes-RPC inter-vm client for the pass password manager.\n\npositional arguments:\n  {mv,cp,init,rm,get-or-generate,show,ls,list,generate,insert}\n                        sub-command help (run subcommand with --help as first parameter)\n    mv                  renames / moves a key in the store\n    cp                  renames / copies a key in the store to a new location\n    init                initializes a new pass store if none exists\n    rm                  removes a key in the store\n    get-or-generate     retrieves a key from the password store, generating one if it does not exist\n    show                shows existing password\n    ls (list)           lists passwords\n    generate            generates a key in the password store\n    insert              inserts a new key into the pass store\n\noptional arguments:\n  -h, --help            show this help message and exit\n  -d DEST_VM, --dest-vm DEST_VM\n                        Set the Qubes domain to operate with.\n\n"
     echo
 
   fi
 }
 
+# :command.usage
+risq_verify_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "risq verify - Verify an onion link signature\n"
+    echo
+
+  else
+    printf "risq verify - Verify an onion link signature\n"
+    echo
+
+  fi
+
+  printf "Usage:\n"
+  printf "  risq verify ONION [options]\n"
+  printf "  risq verify --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_flags
+    # :flag.usage
+    echo "  --key, -k"
+    printf "    Optional public key file to import in keyring, to check the link against\n"
+    echo
+
+    # :flag.usage
+    echo "  --verbose, -v"
+    printf "    Show verbose logging\n"
+    echo
+
+    # :command.usage_args
+    printf "Arguments:\n"
+
+    # :argument.usage
+    echo "  ONION"
+    printf "    onion link to verify (any path component will be removed)\n"
+    echo
+
+  fi
+}
+
+# :command.normalize_input
 normalize_input() {
   local arg flags
 
@@ -96,7 +158,7 @@ normalize_input() {
     shift
   done
 }
-
+# :command.inspect_args
 inspect_args() {
   readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
   if (( ${#args[@]} )); then
@@ -116,6 +178,8 @@ inspect_args() {
   fi
 }
 
+# :command.user_lib
+# src/lib/config.sh
 config_init() {
     RISQ_CONFIG_FILE=${RISQ_CONFIG_FILE-${RISQ_DIR}/config.ini}
     [[ -f "$RISQ_CONFIG_FILE" ]] || {
@@ -237,6 +301,8 @@ config_keys() {
 config_has_key() {
     [[ $(config_get "$1") ]]
 }
+
+# src/lib/log.sh
 
 
 # Section is set either by functions or simple calls,
@@ -396,6 +462,8 @@ function _print() {
     return 0
 }
 
+# src/lib/pass.sh
+
 # Ask the vault to show the ouput of a password
 pass_show ()
 {
@@ -426,6 +494,92 @@ pass_show_once ()
     echo "Local clipboard will be erased after 1 use"
 }
 
+# src/lib/run.sh
+
+COMMAND_STDOUT=''           # Stores a command's stdout output.
+COMMAND_STDERR=''           # Stores a command's stderr output.
+
+# do a command, splitting and storing stdout/stderr output and printing
+# the former to screen only if the command is ran with verbose flag.
+# Returns the command's exit code, so we can catch any errors and inform.
+_run ()
+{
+    # The STDOUT/STDERR variables are populated, which
+    # makes their content available to any subsequent call
+    # to _failure, which needs STDERR output
+    {
+        IFS=$'\n' read -r -d '' COMMAND_STDERR;
+        IFS=$'\n' read -r -d '' COMMAND_STDOUT;
+        (IFS=$'\n' read -r -d '' _ERRNO_; exit "${_ERRNO_}");
+    } < <((printf '\0%s\0%d\0' "$("$@")" "${?}" 1>&2) 2>&1)
+
+    local ret="$?"
+
+    # Output the command's result depending on the verbose mode
+    # and if the command ran successfully. We check that either
+    # stdout or stderr are non-empty: sometimes commands might
+    # output to stderr, like wipe.
+    if [[ $ret -eq 0 ]] && is_verbose_set ; then
+        if [[ -n "$COMMAND_STDOUT" ]]; then
+            _verbose "$COMMAND_STDOUT"
+        fi
+    fi
+
+    # Return the command's exit code
+    return $ret
+}
+
+# Checks the return code of a command, and if not successful,
+# fails with the associated error message. Usage:
+# catch $ret "hush" "Failed to execute this command"
+function _catch ()
+{
+    local ret="$?"
+
+    if [[ ! $ret -eq 0 ]]; then
+        _failure "$@"
+    fi
+}
+
+# src/lib/url.sh
+
+# get_url_host removes the protocol, path and ports from a URI and returns the result
+get_url_host ()
+{
+    # url="$1"
+
+    protocol=$(echo "$1" | grep "://" | sed -e's,^\(.*://\).*,\1,g')
+    # Remove the protocol
+    url_no_protocol=$(echo "${1/$protocol/}")
+    # Use tr: Make the protocol lower-case for easy string compare
+    protocol=$(echo "$protocol" | tr '[:upper:]' '[:lower:]')
+
+    # Extract the user and password (if any)
+    # cut 1: Remove the path part to prevent @ in the querystring from breaking the next cut
+    # rev: Reverse string so cut -f1 takes the (reversed) rightmost field, and -f2- is what we want
+    # cut 2: Remove the host:port
+    # rev: Undo the first rev above
+
+    userpass=$(echo "$url_no_protocol" | grep "@" | cut -d"/" -f1 | rev | cut -d"@" -f2- | rev)
+    # pass=$(echo "$userpass" | grep ":" | cut -d":" -f2)
+    # if [ -n "$pass" ]; then
+    #     user=$(echo "$userpass" | grep ":" | cut -d":" -f1)
+    # else
+    #     user="$userpass"
+    # fi
+
+    # Extract the host
+    hostport=$(echo "${url_no_protocol/$userpass@/}" | cut -d"/" -f1)
+    host=$(echo "$hostport" | cut -d":" -f1)
+    # port=$(echo "$hostport" | grep ":" | cut -d":" -f2)
+    # path=$(echo "$url_no_protocol" | grep "/" | cut -d"/" -f2-)
+
+    # Print the URL host string
+    print "$host"
+}
+
+# src/lib/utils.sh
+
 # Return 0 if is set, 1 otherwise
 option_is_set() {
     local -i r	 # the return code (0 = set, 1 = unset)
@@ -440,9 +594,29 @@ option_is_set() {
     return $r;
 }
 
+# src/lib/validations/url.sh
+
+# validate_onion_v3 accepts a URL host location (without path)
+# and check that it is a valid Onion V3 link.
+validate_onion_v3 ()
+{
+    local host
+
+    # First trim any path and protocol from the link
+    host="$(get_url_host "$1")"
+
+    if [[ ! "$host" =~ ^[a-z2-7]{56}.onion ]] ; then
+        echo "URL is not a valid Onion V3 link"
+    fi
+}
+
+# :command.command_functions
+# :command.function
 risq_pass_command() {
+  # src/pass_command.sh
 
   local command arguments
+
   command="${args[command]}"
   arguments=( "${other_args[@]}" )
 
@@ -453,8 +627,53 @@ risq_pass_command() {
 
 }
 
-parse_requirements() {
+# :command.function
+risq_verify_command() {
+  # src/verify_command.sh
 
+  local onion host tmp
+
+  # The onion argument has been validated as an onion V3 link already,
+  # but we still need the host string without any URL path component.
+  onion="${args[onion]}"
+  host="$(get_url_host "$onion")"
+
+  _message "Verifying Onion link"
+
+  # Fist locate ourselves in a temp directory in which to download stuff
+  tmp="$(mktemp -d -q --suffix risq)"
+  cd "$tmp" || _failure "Failed to cd into temp directory $tmp"
+
+  # 1 - Get the GPG public key associated to this onion. =================================================
+  # * Either ghlkgfjlf.onion/pgp.txt
+  # * Or fetched from another site
+  # * Or specified with --key flag
+  # * Or we might already have a key in our keyring for this: either fallback to this or check if we have one.
+  _message "Fetching GPG public keys"
+
+  # If we need to fetch the GPG key on the site itself
+  _run torify wget "${host}/pgp.txt"
+
+  # 2 - Get the signature file for this onion (generally mirrors.txt) =================================================
+  # In this signature file we must:
+  # - Find all onion links.
+  # - Find that one of those links matches the link we passed as argument.
+  _message "Fetching signature file and ensuring URL match"
+
+  # 3 - Import the GPG public key in our vault keyring =================================================
+  _message "Importing GPG public key in keyring"
+
+  # 4 - Check the signature file against the newly imported key. =================================================
+  _message "Verifying signatures match"
+
+  # 5 - At this point, in all likelihood our site is legit
+  _success "Onion URL verified against GPG key"
+
+}
+
+# :command.parse_requirements
+parse_requirements() {
+  # :command.fixed_flags_filter
   case "${1:-}" in
   --version | -v )
     version_command
@@ -469,11 +688,21 @@ parse_requirements() {
 
   esac
 
+  # :command.dependencies_filter
   if ! [[ -x "$(command -v qvm-pass)" ]]; then
     printf "missing dependency: qvm-pass\n"
     exit 1
   fi
+  if ! [[ -x "$(command -v qubes-gpg-client-wrapper)" ]]; then
+    printf "missing dependency: qubes-gpg-client-wrapper\n"
+    exit 1
+  fi
+  if ! [[ -x "$(command -v qubes-gpg-import-key)" ]]; then
+    printf "missing dependency: qubes-gpg-import-key\n"
+    exit 1
+  fi
 
+  # :command.command_filter
   action=${1:-}
 
   case $action in
@@ -487,6 +716,14 @@ parse_requirements() {
     shift $#
     ;;
 
+  verify )
+    action="verify"
+    shift
+    risq_verify_parse_requirements "$@"
+    shift $#
+    ;;
+
+  # :command.command_fallback
   "" )
     risq_usage
     exit 1
@@ -499,6 +736,7 @@ parse_requirements() {
 
   esac
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -509,7 +747,8 @@ parse_requirements() {
       ;;
 
     * )
-
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
 
@@ -520,8 +759,9 @@ parse_requirements() {
 
 }
 
+# :command.parse_requirements
 risq_pass_parse_requirements() {
-
+  # :command.fixed_flags_filter
   case "${1:-}" in
   --help | -h )
     long_usage=yes
@@ -531,8 +771,10 @@ risq_pass_parse_requirements() {
 
   esac
 
+  # :command.command_filter
   action="pass"
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -543,7 +785,8 @@ risq_pass_parse_requirements() {
       ;;
 
     * )
-
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_catch_all
       if [[ -z ${args[command]+x} ]]; then
 
         args[command]=$1
@@ -560,10 +803,83 @@ risq_pass_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+risq_verify_parse_requirements() {
+  # :command.fixed_flags_filter
+  case "${1:-}" in
+  --help | -h )
+    long_usage=yes
+    risq_verify_usage
+    exit
+    ;;
+
+  esac
+
+  # :command.command_filter
+  action="verify"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+    # :flag.case
+    --key | -k )
+
+      # :flag.case_no_arg
+      args[--key]=1
+      shift
+      ;;
+
+    # :flag.case
+    --verbose | -v )
+
+      # :flag.case_no_arg
+      args[--verbose]=1
+      shift
+      ;;
+
+    -?* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+
+    * )
+      # :command.parse_requirements_case
+      # :command.parse_requirements_case_simple
+      if [[ -z ${args[onion]+x} ]]; then
+        # :argument.validations
+        if [[ -n $(validate_onion_v3 "$1") ]]; then
+          printf "validation error in %s:\n%s\n" "ONION" "$(validate_onion_v3 "$1")"
+          exit 1
+        fi
+
+        args[onion]=$1
+        shift
+      else
+        printf "invalid argument: %s\n" "$key"
+        exit 1
+      fi
+
+      ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args[onion]+x} ]]; then
+    printf "missing required argument: ONION\nusage: risq verify ONION [options]\n"
+    exit 1
+  fi
+
+}
+
+# :command.initialize
 initialize() {
   version="0.1.0"
   long_usage=''
   
+
+  # src/initialize.sh
 
   # Connected terminal
   typeset -H _TTY
@@ -605,6 +921,7 @@ initialize() {
 
 }
 
+# :command.run
 run() {
   declare -A args=()
   declare -a other_args=()
@@ -618,6 +935,14 @@ run() {
       risq_pass_usage
     else
       risq_pass_command
+    fi
+
+  elif [[ $action == "verify" ]]; then
+    if [[ ${args[--help]:-} ]]; then
+      long_usage=yes
+      risq_verify_usage
+    else
+      risq_verify_command
     fi
 
   elif [[ $action == "root" ]]; then
